(define (problem prob-matrix-visible)
(:domain mars-exploration)
(:objects x0 x1 x2 y0 y1 y2
          soil-container rock-container 
          battery
          level-70 level-60 level-50 level-40 level-30 level-20 level-10 level-0 
          panel1 panel2 panel3 panel4
          soil storage
          none thin medium thick
)
(:init 
    (loc x0)
    (loc x1)
    (loc x2)
    (loc y0)
    (loc y1)
    (loc y2)

    (at x0 y0)
    
    (connection x0 x0)
    (connection x0 x1)
    (connection x1 x2)
    (connection x2 x1)
    (connection x1 x0)
    (connection y0 y0)
    (connection y0 y1)
    (connection y1 y2)
    (connection y2 y1)
    (connection y1 y0)

    (unknown (soil-analysed x0 y1))
    (unknown (soil-analysed x0 y2))
    (unknown (soil-analysed x1 y0))
    (unknown (soil-analysed x1 y1))
    (unknown (soil-analysed x1 y2))
    (unknown (soil-analysed x2 y0))
    (unknown (soil-analysed x2 y1))
    (unknown (soil-analysed x2 y2))

    (unknown (rock-analysed x0 y1))
    (unknown (rock-analysed x0 y2))
    (unknown (rock-analysed x1 y0))
    (unknown (rock-analysed x1 y1))
    (unknown (rock-analysed x1 y2))
    (unknown (rock-analysed x2 y0))
    (unknown (rock-analysed x2 y1))
    (unknown (rock-analysed x2 y2))

    (unknown (image-taken x0 y1))
    (unknown (image-taken x0 y2))
    (unknown (image-taken x1 y0))
    (unknown (image-taken x1 y1))
    (unknown (image-taken x1 y2))
    (unknown (image-taken x2 y0))
    (unknown (image-taken x2 y1))
    (unknown (image-taken x2 y2))

    (unknown (visited x0 y1))
    (unknown (visited x0 y2))
    (unknown (visited x1 y0))
    (unknown (visited x1 y1))
    (unknown (visited x1 y2))
    (unknown (visited x2 y0))
    (unknown (visited x2 y1))
    (unknown (visited x2 y2))

    (visited x0 y0)

    (soil-container soil-container)
    (rock-container rock-container)
    (image-storage storage)
    (empty soil-container)
    (empty rock-container)
     
    (level level-70)
    (level level-60)
    (level level-50)
    (level level-40)
    (level level-30)
    (level level-20)
    (level level-10)
    (level level-0)
    
    (easy-rock x0 y0)
    (easy-rock x0 y1)
    (easy-rock x0 y2)
    (medium-rock x1 y0)
    (medium-rock x1 y1)
    (medium-rock x1 y2)
    (hard-rock x2 y0)
    (hard-rock x2 y1)
    (hard-rock x2 y2)
    (medium-soil x0 y0)
    (medium-soil x0 y1)
    (medium-soil x0 y2)
    (hard-soil x1 y0)
    (hard-soil x1 y1)
    (hard-soil x1 y2)
    (easy-soil x2 y0)
    (easy-soil x2 y1)
    (easy-soil x2 y2)

    (next-easy level-70 level-60)
    (next-easy level-60 level-50)
    (next-easy level-50 level-40)
    (next-easy level-40 level-30)
    (next-easy level-30 level-20)
    (next-easy level-20 level-10)
    (next-easy level-10 level-0)

    (next-medium level-70 level-50)
    (next-medium level-60 level-40)
    (next-medium level-50 level-30)
    (next-medium level-40 level-20)
    (next-medium level-30 level-10)
    (next-medium level-20 level-0)
    (next-medium level-10 level-0)

    (next-hard level-70 level-40)
    (next-hard level-60 level-30)
    (next-hard level-50 level-20)
    (next-hard level-40 level-10)
    (next-hard level-30 level-0)
    (next-hard level-20 level-0)
    (next-hard level-10 level-0)

    (battery battery)
    (battery-level battery level-70)  ;change

    (next-charge level-0 level-70)
    (next-charge level-10 level-70)
    (next-charge level-20 level-70)
    (next-charge level-30 level-70)
    (next-charge level-40 level-70)
    (next-charge level-50 level-70)
    (next-charge level-60 level-70)
    (next-charge level-70 level-70)

    (next-charge level-20 level-70)
    (next-charge level-30 level-70)
    (next-charge level-40 level-70)
    (next-charge level-50 level-70)
    (next-charge level-60 level-70)
    (next-charge level-70 level-70)

    (critical level-20)
    (critical level-10)
    (critical level-0)

    (panel panel1)
    (panel panel2)
    (panel panel3)
    (panel panel4)

    (unknown (max-light panel1))
    (unknown (max-light panel2))
    (unknown (max-light panel3))
    (unknown (max-light panel4))

    (oneof
        (max-light panel1)
        (max-light panel2)
        (max-light panel3)
        (max-light panel4)
    )

    (dust-thickness none)
    (dust-thickness thin)
    (dust-thickness medium)
    (dust-thickness thick)

    (dust-next none thin)
    (dust-next thin medium)
    (dust-next medium thick)

    (windwhirl-at x1 y1)
    (windwhirl-at x1 y2)

    (dust-at x1 y1)
    (dust-at x0 y1)

    (dust-on-panels none)

    ;(none-dust-thickness none)
    ;(min-dust-thickness thin)
    ;(medium-dust-thickness medium)
    (max-dust-thickness thick)
)
(:goal
    (and
        (soil-analysed x0 y1)
        (rock-analysed x0 y1)
        (soil-analysed x0 y2)
        (soil-analysed x1 y0)
        (rock-analysed x2 y0)
        (visited x0 y1)
        (image-taken x1 y2)
        (image-taken x0 y1)
        (image-taken x1 y1)
    )
)
)

